@startuml Shopee

' Pakkediagram som viser de ulike pakkene som ligger i de 
' ulike modulene og hvilke pakker som ligger i dem.
' Litt usikker på strukturen, og her må vi endre på 
' mappestrukturen i prosjektet for at dette diagrammet skal
' funke.

component ui {
    package shopee.ui
}

component core{
    package shopee.core
    package shopee.json
}

component jackson {
}

component javafx {
    component fxml {

    }
}

component restapi {
    package shopee.rest {

    }
}

component springboot {
}



shopee.ui ..> shopee.core
ui ..> javafx
ui ..> fxml
shopee.core ..> shopee.json
shopee.json ..> jackson
shopee.rest ..> springboot
shopee.rest ..> shopee.core
shopee.rest ..> shopee.json
ui ..> shopee.rest 
shopee.ui ..> shopee.json

@enduml