@startuml Shopee


 skinparam Style strictuml
 skinparam SequenceMessageAlignment center



 actor User 
 User -> Login : User Info
 Login -> Storage : Sign Up
 Storage --> Storage : Save New User
 Storage --> HomePage : Log in
 Login -> HomePage: Log In
 HomePage -> ShopeeList : Create/Edit/Display ShopeeList
 ShopeeList -> ShopeeList : Add/Del/Buy FoodItem 
 ShopeeList -> Storage : Saves list continuously
 ShopeeList -> HomePage : Back to Home
 

 'This might be the wrong representation of the restapi??
 User -> RESTAPI : HTTP Request
 RESTAPI --> Storage : Retrieve User Data
 Storage --> RESTAPI : User Data
 RESTAPI --> User : HTTP Response


 loop endre
 alt Want to change more lists
     HomePage -> ShopeeList : edit 
 else want to log out
     HomePage -> Login
end 

@enduml

